version: '3.5'
services:
  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672 # management plugin
    networks:
      - messaging
  producer:
    build: producer
    environment:
      RABBITMQ_HOST: rabbit
      EXCHANGE_NAME: events
      MESSAGE_PERIOD: 5000
    networks:
      - messaging
  odd-consumer:
    build: consumer
    environment:
      RABBITMQ_HOST: rabbit
      EXCHANGE_NAME: events
      BINDING_KEY: number.odd
    networks:
      - messaging
  even-consumer:
    build: consumer
    environment:
      RABBITMQ_HOST: rabbit
      EXCHANGE_NAME: events
      BINDING_KEY: number.even
    networks:
      - messaging
networks:
  messaging: