version: '3.5'
services:
  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672 # management plugin
    networks:
      - messaging
  producer:
    build: producer
    volumes:
      - maven-cache:/root/.m2
    environment:
      RABBITMQ_HOST: rabbit
      QUEUE_NAME: messages
      MESSAGE_PERIOD: 2000
    networks:
      - messaging
  consumer:
    build: consumer
    volumes:
      - maven-cache:/root/.m2
    environment:
      RABBITMQ_HOST: rabbit
      QUEUE_NAME: messages
    networks:
      - messaging
volumes:
  maven-cache:
networks:
  messaging: